import { Component, Input, OnInit } from '@angular/core';
import { Event } from '../event';
import { EventService } from '../event.service';


@Component({
  selector: 'app-summary',
  templateUrl: './summary.component.html',
  styleUrls: ['./summary.component.css'], 
  providers: [EventService]
})
export class SummaryComponent{


  htmlYouWantToAdd: string = "";

  addHTML(){
    if(this.eService.EVENTS[0].game == "Rocket League"){
      this.htmlYouWantToAdd = "<h5>"+ this.eService.getStatsRL()[2] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Shots</th><th scope=\"col\">Saves</th><th scope=\"col\">Goals</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsRL()[0][0][0] +"</th><td>"+ this.eService.getStatsRL()[0][0][1] +"</td><td>"+ this.eService.getStatsRL()[0][0][2] +"</td><td>"+ this.eService.getStatsRL()[0][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsRL()[0][1][0] +"</th><td>"+ this.eService.getStatsRL()[0][1][1] +"</td><td>"+ this.eService.getStatsRL()[0][1][2] +"</td><td>"+ this.eService.getStatsRL()[0][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsRL()[0][2][0] +"</th><td>"+ this.eService.getStatsRL()[0][2][1] +"</td><td>"+ this.eService.getStatsRL()[0][2][2] +"</td><td>"+ this.eService.getStatsRL()[0][2][3] +"</td></tr></tbody></table>"
      this.htmlYouWantToAdd += "<br><h5>"+ this.eService.getStatsRL()[3] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Shots</th><th scope=\"col\">Saves</th><th scope=\"col\">Goals</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsRL()[1][0][0] +"</th><td>"+ this.eService.getStatsRL()[1][0][1] +"</td><td>"+ this.eService.getStatsRL()[1][0][2] +"</td><td>"+ this.eService.getStatsRL()[1][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsRL()[1][1][0] +"</th><td>"+ this.eService.getStatsRL()[1][1][1] +"</td><td>"+ this.eService.getStatsRL()[1][1][2] +"</td><td>"+ this.eService.getStatsRL()[1][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsRL()[1][2][0] +"</th><td>"+ this.eService.getStatsRL()[1][2][1] +"</td><td>"+ this.eService.getStatsRL()[1][2][2] +"</td><td>"+ this.eService.getStatsRL()[1][2][3] +"</td></tr></tbody></table>"
    }
    else if(this.eService.EVENTS[0].game == "Valorant"){
      this.htmlYouWantToAdd = "<h5>"+ this.eService.getStatsVal()[2] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Spike Plant</th><th scope=\"col\">Elimination</th><th scope=\"col\">Utility Used</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsVal()[0][0][0] +"</th><td>"+ this.eService.getStatsVal()[0][0][1] +"</td><td>"+ this.eService.getStatsVal()[0][0][2] +"</td><td>"+ this.eService.getStatsVal()[0][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsVal()[0][1][0] +"</th><td>"+ this.eService.getStatsVal()[0][1][1] +"</td><td>"+ this.eService.getStatsVal()[0][1][2] +"</td><td>"+ this.eService.getStatsVal()[0][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsVal()[0][2][0] +"</th><td>"+ this.eService.getStatsVal()[0][2][1] +"</td><td>"+ this.eService.getStatsVal()[0][2][2] +"</td><td>"+ this.eService.getStatsVal()[0][2][3] +"</td></tr></tbody></table>"
      this.htmlYouWantToAdd += "<br><h5>"+ this.eService.getStatsVal()[3] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Spike Plant</th><th scope=\"col\">Elimination</th><th scope=\"col\">Utility Used</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsVal()[1][0][0] +"</th><td>"+ this.eService.getStatsVal()[1][0][1] +"</td><td>"+ this.eService.getStatsVal()[1][0][2] +"</td><td>"+ this.eService.getStatsVal()[1][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsVal()[1][1][0] +"</th><td>"+ this.eService.getStatsVal()[1][1][1] +"</td><td>"+ this.eService.getStatsVal()[1][1][2] +"</td><td>"+ this.eService.getStatsVal()[1][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsVal()[1][2][0] +"</th><td>"+ this.eService.getStatsVal()[1][2][1] +"</td><td>"+ this.eService.getStatsVal()[1][2][2] +"</td><td>"+ this.eService.getStatsVal()[1][2][3] +"</td></tr></tbody></table>"
    }
    else if(this.eService.EVENTS[0].game == "Hockey"){
      this.htmlYouWantToAdd = "<h5>"+ this.eService.getStatsHoc()[2] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Shots</th><th scope=\"col\">Saves</th><th scope=\"col\">Goals</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsHoc()[0][0][0] +"</th><td>"+ this.eService.getStatsHoc()[0][0][1] +"</td><td>"+ this.eService.getStatsHoc()[0][0][2] +"</td><td>"+ this.eService.getStatsHoc()[0][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsHoc()[0][1][0] +"</th><td>"+ this.eService.getStatsHoc()[0][1][1] +"</td><td>"+ this.eService.getStatsHoc()[0][1][2] +"</td><td>"+ this.eService.getStatsHoc()[0][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsHoc()[0][2][0] +"</th><td>"+ this.eService.getStatsHoc()[0][2][1] +"</td><td>"+ this.eService.getStatsHoc()[0][2][2] +"</td><td>"+ this.eService.getStatsHoc()[0][2][3] +"</td></tr></tbody></table>"
      this.htmlYouWantToAdd += "<br><h5>"+ this.eService.getStatsHoc()[3] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Shots</th><th scope=\"col\">Saves</th><th scope=\"col\">Goals</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsHoc()[1][0][0] +"</th><td>"+ this.eService.getStatsHoc()[1][0][1] +"</td><td>"+ this.eService.getStatsHoc()[1][0][2] +"</td><td>"+ this.eService.getStatsHoc()[1][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsHoc()[1][1][0] +"</th><td>"+ this.eService.getStatsHoc()[1][1][1] +"</td><td>"+ this.eService.getStatsHoc()[1][1][2] +"</td><td>"+ this.eService.getStatsHoc()[1][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsHoc()[1][2][0] +"</th><td>"+ this.eService.getStatsHoc()[1][2][1] +"</td><td>"+ this.eService.getStatsHoc()[1][2][2] +"</td><td>"+ this.eService.getStatsHoc()[1][2][3] +"</td></tr></tbody></table>"
    }
    else if(this.eService.EVENTS[0].game == "Basketball"){
      this.htmlYouWantToAdd = "<h5>"+ this.eService.getStatsBas()[2] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Shots</th><th scope=\"col\">Stops</th><th scope=\"col\">Baskets</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsBas()[0][0][0] +"</th><td>"+ this.eService.getStatsBas()[0][0][1] +"</td><td>"+ this.eService.getStatsBas()[0][0][2] +"</td><td>"+ this.eService.getStatsBas()[0][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsBas()[0][1][0] +"</th><td>"+ this.eService.getStatsBas()[0][1][1] +"</td><td>"+ this.eService.getStatsBas()[0][1][2] +"</td><td>"+ this.eService.getStatsBas()[0][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsBas()[0][2][0] +"</th><td>"+ this.eService.getStatsBas()[0][2][1] +"</td><td>"+ this.eService.getStatsBas()[0][2][2] +"</td><td>"+ this.eService.getStatsBas()[0][2][3] +"</td></tr></tbody></table>"
      this.htmlYouWantToAdd += "<br><h5>"+ this.eService.getStatsBas()[3] +"</h5><table class=\"table\"><thead><tr><th scope=\"col\">Player</th><th scope=\"col\">Shots</th><th scope=\"col\">Stops</th><th scope=\"col\">Baskets</th></tr></thead><tbody><tr><th scope=\"row\">"+ this.eService.getStatsBas()[1][0][0] +"</th><td>"+ this.eService.getStatsBas()[1][0][1] +"</td><td>"+ this.eService.getStatsBas()[1][0][2] +"</td><td>"+ this.eService.getStatsBas()[1][0][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsBas()[1][1][0] +"</th><td>"+ this.eService.getStatsBas()[1][1][1] +"</td><td>"+ this.eService.getStatsBas()[1][1][2] +"</td><td>"+ this.eService.getStatsBas()[1][1][3] +"</td></tr><tr><th scope=\"row\">"+ this.eService.getStatsBas()[1][2][0] +"</th><td>"+ this.eService.getStatsBas()[1][2][1] +"</td><td>"+ this.eService.getStatsBas()[1][2][2] +"</td><td>"+ this.eService.getStatsBas()[1][2][3] +"</td></tr></tbody></table>"
    }
  }

  // @Input() shots: number = this.getTotalShots();

  constructor(private eService: EventService) {}

}
